server:
  port: 80
spring:
  datasource:
    username: username
    password: password
    hikari:
      connection-test-query: SELECT 1
      max-lifetime: 300000
      idle-timeout: 60000
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: update
feign.autoconfiguration.jackson.enabled: true
---
spring:
  config:
    activate:
      on-profile: docker-compose
  datasource:
    url: jdbc:postgresql://pg:5432/kc
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.3:8081/auth/realms/tc-dev
          jwk-set-uri: http://kc:8080/auth/realms/tc-dev/protocol/openid-connect/certs
---
spring:
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: jdbc:postgresql://pg-postgresql-ha-pgpool:5432/em
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://139.59.221.89/auth/realms/tc-dev
          jwk-set-uri: http://kc-keycloak/auth/realms/tc-dev/protocol/openid-connect/certs