oidc:
  clientId: sfm
  url: ${auth_url}/auth/realms/sfm
server:
  port: 80
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    username: username
    password: password
    hikari:
      connection-test-query: SELECT 1
      minimumIdle: 5
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
  jpa:
    hibernate:
      ddl-auto: none
feign.autoconfiguration.jackson.enabled: true
logging:
  level:
    root: Error
---
spring:
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: jdbc:postgresql://${db_host}:5432/em
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth_url}/auth/realms/tc-dev
          jwk-set-uri: http://${keycloak_host}/auth/realms/tc-dev/protocol/openid-connect/certs